on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Python setup ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install PoseVis
        run: |
          cd devices/webcam
          python setup.py install
      - name: Run PoseVis tests
        run: |
          cd devices/webcam
          python -m unittest pose_vis/test/tests.py